FROM tiangolo/uvicorn-gunicorn-fastapi:python3.11

WORKDIR /app

COPY /core_lib/requirements.txt requirements.txt
RUN pip install -r requirements.txt
COPY /core_lib /usr/local/lib/python3.11/site-packages/core_lib

COPY /notification_service/requirements.txt requirements.txt
RUN pip install -r requirements.txt

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "80", "--reload", "--workers", "4"]
